### ISSUE TITLE
line between 2 values

### ISSUE THREAD

**Issue by dinogit** [chartjs/chartjs-plugin-annotation#100]
Hi 

Is there any options to move line between 2 values, something like margin-right?

In this case line needs to be between 2016-07 and 207-01.

![chart-9](https://user-images.githubusercontent.com/1814086/33602143-b28ea354-d9ae-11e7-8a7a-d24266f622a7.png)

**Comment by dinogit** [comment]
fix this with draggable plugin

**Comment by phil-w** [comment]
Draggable allows a human to drag the line, but what if the line is actually in the wrong place and needs to be put between the points? Example: the median line when you have an even number of points. Asking the users to drag the line to where it should be is perhaps not great.

Is there a way to place a vertical line *between* two x-axis points? I can make the line fatter with borderWidth, but it grows from the centre of the point, so that won't actually solve the issue.
