### ISSUE TITLE
Feature request: Annotation z-index

### ISSUE THREAD

**Issue by michealjroberts** [chartjs/chartjs-plugin-annotation#175]
I've noticed that the annotation line is somehow z-indexed on the Canvas higher than the hover tooltips for the normal Chart.js line tooltips.

**Comment by johnmifit** [comment]
I agree, it appears that sometimes boxes are being layer in front of lines even though the lines are further back in the `annotations` array.

**Comment by diegoiglesias** [comment]
+1

**Comment by sheadawson** [comment]
+1

**Comment by sheadawson** [comment]
I just had this issue with boxes drawing over my line graph lines. Quick fix: add this before adding your annotations

`chart.ctx.globalCompositeOperation='destination-over';`

**Comment by sheadawson** [comment]
Still had a weird issue with the hover tooltips. Worked around with custom html tooltips https://www.chartjs.org/samples/latest/tooltips/custom-line.html

**Comment by firebird631** [comment]
I have the same issue, the annotation line appears above the hover toolip and I find no option to control that.

**Comment by kurkle** [comment]
@firebird631 what is your `drawTime` set to?

**Comment by firebird631** [comment]
@kurkle I don't understand, all is ok today :) But I have no idea of what I have changed that fix it. I'll make a reply if I found what was the mistake.

**Comment by shmkane** [comment]
Was there ever a solution to this?

**Comment by elitastic** [comment]
Yes, drawTime should be set to "beforeDraw"!

**Comment by stockiNail** [comment]
Even if the `drawTime` could solve some use cases, it could happen that more annotations must be drawn at the same `drawTime` (in order to be consistent with the other elements of the chart) but one annotation can not be visible because the another annotation is drawn on top.

See codepen: https://codepen.io/stockinail/pen/PoJoMbr

In the sample, the point annotation is not visible because the box one is drawn on the same "area".
The workaround is to put the annotations config in the order of drawing. 
Nevertheless it sounds to me just a workaround.
For this use case, I think it could be better to add `z` option to the annotations in order to draw the annotations in the desired order.

**Comment by kurkle** [comment]
I agree, but the `z` should be global to the chart and thus be supported in the core too. I would not want to end up having inconsistent z option in every plugin.

I think one way of doing that is:

- collect all the z values in use
- call draw with each z value for each dataset/scale/plugin in order.

Probably a breaking change.

**Comment by stockiNail** [comment]
@kurkle sounds good to me. 
Of course, this will be delegated to the CHARTJS engine and a "standard" configuration (all the options of these elements should contain `z` option or whatever else, if I have understood well what you meant) would be  needed among the elements.
