### ISSUE TITLE
Cannot read property options of undefined

### ISSUE THREAD

**Issue by codeofsumit** [chartjs/chartjs-plugin-annotation#219]
HI there,

first of all: thanks for this awesome plugin! Great job 👏 .

Wanted to report a small bug. Seems like the plugin is expecting `annotations` object in every chart?

![image](https://user-images.githubusercontent.com/2399810/83615749-43824400-a587-11ea-8ea4-e1c4af16946b.png)

**Comment by zhicong** [comment]
I've been seeing this error randomly too, along with another likely related one: `TypeError: Cannot read property 'supported' of undefined`

It's probably from this line, and the same root cause:
https://github.com/chartjs/chartjs-plugin-annotation/blob/75436541ab1424ea02903fb772c37b5378484603/chartjs-plugin-annotation.js#L66

I'll try fixing this by declaring the annotation plugin only if I have annotations in the `annotations` array. This issue doesn't reproduce 100% for me, so I can't tell right away if this fixes it.

**Comment by olivertilk** [comment]
I started seeing the same two errors above and it turned out the problem was I just forgot to import chartjs-plugin-annotation.
