### ISSUE TITLE
Demos are not running :-(

### ISSUE THREAD

**Issue by btcorgtfo** [chartjs/chartjs-plugin-annotation#240]
hi, first of all: thanks for the great work :-)

however, i am unable to run one any of the html demos included. each console log terminates with the same error.

i build the package via npm, so all the .js files are in the dist folder and can be found, also chart.js from the node_modules folder.

Anyway: each sample html gives me the following error:

```
Uncaught TypeError: Cannot read property 'annotations' of undefined
    at getAnnotationOptions (chartjs-plugin-annotation.js:611)
    at adjustScaleRange (chartjs-plugin-annotation.js:615)
    at LinearScale.scale.afterDataLimits (chartjs-plugin-annotation.js:600)
    at LinearScale.update (chart.js:5459)
    at fitBoxes (chart.js:2839)
    at Object.update (chart.js:2951)
    at Chart._updateLayout (chart.js:7123)
    at Chart.update (chart.js:7104)
    at new Chart (chart.js:6881)
    at window.onload (bar.html?_ijt=ucoi9hqs3cabhlnslabp2v5fl9:68)

```
Any hint, on how to solve this?

**Comment by joshkel** [comment]
As I understand it, both chart.js and chartjs-plugin-annotation are in rapid development right now, as part of the Chart.js 3.x beta. That unfortunately means that you need to jump through some extra hoops to use the plugin's master branch, because it requires changes from Chart.js that haven't yet been released. Here's what I did:

* Clone chartjs-plugin-annotation from master.
* Run `npm i` to install its dependencies.
* Clone Chart.js from [its master](https://github.com/chartjs/Chart.js/).
* From the Chart.js directory:
    * Run `npm i` to install its dependencies.
    * Run `npm run build` to build it.
    * Manually copy the contents of its `dist` folder to chartjs-plugin-annotations' `node_modules/chart.js/dist` folder.

There are [more robust alternatives](https://www.viget.com/articles/how-to-use-local-unpublished-node-packages-as-project-dependencies/), but this was an easy way to get up and running.

**Comment by stockiNail** [comment]
@btcorgtfo the issue has been solved by https://github.com/chartjs/chartjs-plugin-annotation/pull/246
