### ISSUE TITLE
Set line annotation at specified data point.

### ISSUE THREAD

**Issue by ZhangHao-PonyAI** [chartjs/chartjs-plugin-annotation#284]
I want to set the value of a line annotation equal to a specified data point, can I use a callback function which has the context containing the chart when set the value item in annotation config?

**Comment by stockiNail** [comment]
> I want to set the value of a line annotation equal to a specified data point,

@ZhangHao-PonyAI maybe I'm misunderstanding your need. Could you provide any example how this will look like?

**Comment by ZhangHao-PonyAI** [comment]
Yeah, I have some data looks like `d = [(x0, y0), (x1, y1), ..., (xn, yn)]` and want to show them in a line chart. And I also want to render a vertical line at a specified data point, for example, a vertical line `x=d[1].x`, as data I get may change, so how can I get the value of `d[${a specified index}].x` to set the position of the vertical line?

**Comment by stockiNail** [comment]
> And I also want to render a vertical line at a specified data point, for example, a vertical line `x=d[1].x`, as data I get may change, so how can I get the value of `d[${a specified index}].x` to set the position of the vertical line?

To do that, the values of annotations should be configured at runtime, as scriptable options. I mentioned this missing feature in the issue #244 because this capability will address your need and will enable to set the dynamic values at runtime, during teh whole chart lifecycle (for instance averages, standard deviations, linear regressions).

I can try to submit a PR for that.

> By the way, I get confuesed by the example in the README.md, there is a horizontal line which seems y = -50, but I found that in the line annotations config value: 25..? 

If you are referring to the picture of the chart and the source code reported as example, as far as I see the source is not related to the picture.

> And the CodePen link opens abnormally, is it just my network problem?

I can open it and sounds working correctly. Be aware that CodePen is using the plugin version 0.5.7 and not 1.0.0.beta*

**Comment by stockiNail** [comment]
@ZhangHao-PonyAI PR #316 submitted. Have a look if make sense for you as well.

**Comment by kurkle** [comment]
With latest pre-release the value is scriptable.

https://codepen.io/kurkle/pen/xxRaMwV

**Comment by stockiNail** [comment]
@kurkle just for my knowledge, are all options "scriptable" now (with beta4)?

**Comment by kurkle** [comment]
@stockiNail yes, except event hooks.
Not covered by tests, not much tested and not documented. Some of the reasons I decided not to advertise that :)

**Comment by stockiNail** [comment]
> @stockiNail yes, except event hooks.
> Not covered by tests, not much tested and not documented. Some of the reasons I decided not to advertise that :)

I agree.. I hope to find out time to do some tests/docs but I'm very busy. I'll do my best!

**Comment by stockiNail** [comment]
> Not covered by tests, not much tested

@kurkle I have added some test cases by PR #349
