### ISSUE TITLE
Are there types for this plugin?

### ISSUE THREAD

**Issue by kurkle** [chartjs/chartjs-plugin-annotation#296]
Are there types for this plugin?

_Originally posted by @paulhayessilex in https://github.com/chartjs/chartjs-plugin-annotation/issues/216#issuecomment-754634882_

**Comment by kurkle** [comment]
Released v1.0.0-beta.2 with the `types` mentioned in `package.json`

Updated https://codesandbox.io/s/condescending-swirles-3swdb to verify the initial types work. 

Please create pull requests if the types are incomplete!

**Comment by joshkel** [comment]
I have a question about the organization of the new type definitions. Because the types are split across a few files, they're awkward to import, if I want to use the types in my own chart-related code that builds on the plugin:

```
import { AnnotationElement } from 'chartjs-plugin-annotation/types/element';
import { EventContext } from 'chartjs-plugin-annotation/types/events';
import { LabelOptions } from 'chartjs-plugin-annotation/types/label';
import { AnnotationOptions } from 'chartjs-plugin-annotation/types/options';
```

I also add some custom annotation properties for use with my plugins, so I used TypeScript's [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) to document the new properties within my code:

```
declare module 'chartjs-plugin-annotation/types/options' {
  interface CoreAnnotationOptions {
    // Add datasetIndex so that we can use custom events to show/hide plot
    // annotations based on their corresponding dataset.
    datasetIndex?: number;
  }
}
```

In all of these cases, the resulting `.../types/foo` suffix makes the code more verbose, and it feels like it's introducing a dependency on the internal layout of chartjs-plugin-annotation, and the organization of the types modules don't really match the organization of the source code.

As I understand it, there are a few options:

1. Import and re-export all of the symbols from `types/index.d.ts`. This would let applications do direct imports ` from 'chartjs-plugin-annotation'`, but declaration merging still requires the path to the original declaration.
2. Use Rollup to combine the `types/**/*.d.ts` files into a single `.d.ts` file under `dist`. This is similar to what Chart.js itself does. This works, but it's a bit awkward for some tooling. (For example, WebStorm's "Go To Declaration or Usages" hotkey usually goes to the imported-and-re-exported symbol within the barely-readable Rollup-generated dist d.ts file, and I have to navigate two more hops to find the actual definitions.)
3. Combine all of the `*.d.ts` files' contents into a single `types/index.d.ts` file.

Option 3 seems best to me; it makes usage much simpler, and chartjs-plugin-annotation is small enough that the combined d.ts file seems manageable.

Any thoughts? I can open a PR implementing one of these options if you like.

**Comment by kurkle** [comment]
@joshkel if the option 1 really requires the path for declaration merging, then I'd be happy to go with option 3.

I guess the same applies to [datalabels plugin types](https://github.com/chartjs/chartjs-plugin-datalabels/blob/chartjs-next/types).
@simonbrunel @etimberg any thoughts?

**Comment by simonbrunel** [comment]
The datalabels plugin implements option 1: split types in multiple files and **export the public API via `index.d.ts`**. I'm a bit surprised that *"declaration merging still requires the path to the original declaration."*. I actually promote using module augmentation for the scriptable `Context`, which is declared in `types/context.d.ts` and made public in [`types/index.d.ts`](https://github.com/chartjs/chartjs-plugin-datalabels/blob/chartjs-next/types/index.d.ts#L24). Declaration merging works as described in [the docs](https://master--chartjs-plugin-datalabels.netlify.app/guide/typescript.html#module-augmentation) using `declare module 'chartjs-plugin-datalabels'` but maybe I'm missing a use case that doesn't work with this approach?

**Comment by joshkel** [comment]
I apologize; I had forgotten some details. I first experimented with declaration merging with Chart.js itself (when it used multiple d.ts files spread across multiple subdirectories, prior to https://github.com/chartjs/Chart.js/pull/8198). The multiple subdirectories in particular were what caused problems for declaration merging.

I'm not entirely certain why the use of subdirectories makes a difference, but the current code keeps type definitions in one directory, and option 1 seems best otherwise (and is consistent with datalabels), so I'll go with that.

Thanks for the feedback.

**Comment by simonbrunel** [comment]
@joshkel If I move `Context.d.ts` under `types/private/Context.d.ts`, it still works with:

```ts
import {Context} from 'chartjs-plugin-datalabels';

declare module 'chartjs-plugin-datalabels' {
  interface Context {
    foo?: number;
  }
}
```

**Comment by joshkel** [comment]
@simonbrunel Interesting. I played around with chart.js and chartjs-plugin-datalabels some more and can reproduce the problem for chart.js's old directory layout but not for the chartjs-plugin-datatables you described. I can't what the difference is, but since I have a solution for current code, I doubt I'll spend more time on it right now.
