### ISSUE TITLE
Annotation Label Content Can't have HTML tags

### ISSUE THREAD

**Issue by sasiel** [chartjs/chartjs-plugin-annotation#318]
The annotation label content supports only text, can it support html tags as well?

**Comment by stockiNail** [comment]
@sasiel the annotation are drawn on the canvas element which, afaik, doesn't support any HTML tag, therefore the labels can be only text.

**Comment by sasiel** [comment]
I see, what the complexity of adding an html tag support? I can help with this PR if needed

**Comment by stockiNail** [comment]
@sasiel it doesn't depend on the complexity. Afaik, but maybe I'm wrong, the canvas element doesn't support HTML tags.

**Comment by sasiel** [comment]
@stockiNail Got it, thank you!

**Comment by stockiNail** [comment]
@sasiel maybe my answer hasn't evaluated the possibility to use SVG (and foreignObject) in order to create an image adding HTML tags into SVG. I have already this way in another project (https://github.com/pepstock-org/Charba/wiki/Utilities#html-annotation-builder).

Another thing is that the plugin defines the label text by `content` option and not `text` one. This is probably ecuase who developed the plugin at the beginning thought do not use only text but also other kind of contents. 

I have coded a prototype, allowing to the plugin to accept an image (this could be helpful also per other purposes).

This is a piece of html page where I'm creating the SVG:

```javascript
const image = new Image();
	image.src = 'data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" width="150" height="60">'+
	'<foreignObject width="100%" height="100%">'+
	'<div xmlns="http://www.w3.org/1999/xhtml">Here is a <strong style="color: white;">paragraph</strong> that requires <em>word wrap</em></div>'+
	'</foreignObject></svg>';
```

Then I have defined a line annotation passing the image into label content:

```javascript
plugins: {
    annotation: {
        annotations: {
            myHorizontalLine: {
                type: 'line',
                scaleID: 'y',
                value: 25,
                borderColor: 'black',
                borderWidth: 5,
                label: {
                    position: 'center',
                    backgroundColor: 'red',
                    content: image, // <-- SVG image
                    enabled: true
                }
            }
        }
    }
}
```

Here is the result:

![svg](https://user-images.githubusercontent.com/11741250/106047330-c2faef80-60e3-11eb-8194-8371488fa5f6.png)

If it makes sense for you, I can try to submit a PR to enable it.
