### ISSUE TITLE
Feature Request: Polygon Annotation

### ISSUE THREAD

**Issue by powerpete** [chartjs/chartjs-plugin-annotation#431]
To mark some areas with different kind of shapes (like triangle etc.), it would be nice to have some polygon annotations.

**Comment by stockiNail** [comment]
@powerpete sorry if I ask you now (after a long time) but I'd like to know from you what polygons (apart of triangle) could be interesting for you.

FYI, in my branch, I had developed the triangle (based on box annotation).

Nevertheless, the use cases (or user needs) could be many and different among them. Maybe it could interesting to think about to enable pluggable annotation types to the this plugin.  

@kurkle what do you think?

**Comment by kurkle** [comment]
Couple of thoughts:

- We could make a `custom` type with configurable draw functions.
- We could have a `annotationElement` base class and let people extend that and look up all the registered elements of that type when initializing the plugin. Not sure about this direction, since it requires opening much of the internals up and thus freezes the internals.

**Comment by stockiNail** [comment]
> * We could make a `custom` type with configurable draw functions.
> 
> * We could have a `annotationElement` base class and let people extend that and look up all the registered elements of that type when initializing the plugin.

Exactly what I was thinking (I'm playing locally to have a prototype).

>     * Not sure about this direction, since it requires opening much of the internals up and thus freezes the internals.

Yes, this is a CONS of this possible solution. I don't know the approach the community wants to use for that. If the above item is an issue, there is not other options (I guess) to code all types inside the project. :)

**Comment by stockiNail** [comment]
@kurkle FYI I have implemented in my branch a PoligonAnnotation which can draw whatever poligon based on circle built with a center point. `inRange` method is not implemented yet because I have to check how to calculate exatcly if a point is inside a poligon.

Apart for common options, it needs `radius` (to have the circle where the poligon is drawn inside it) and `sides` (amount of sides of poligon).

Here is the code:

```javascript
import {Element} from 'chart.js';
import {PI, RAD_PER_DEG} from 'chart.js/helpers';
import {scaleValue} from '../helpers';

export default class PoligonAnnotation extends Element {

  inRange(x, y) {
    const {width, options} = this;
    const center = this.getCenterPoint(true);
    const radius = width / 2 + options.borderWidth;

    if (radius <= 0) {
      return false;
    }

    return (Math.pow(x - center.x, 2) + Math.pow(y - center.y, 2)) <= Math.pow(radius, 2);
  }

  getCenterPoint(useFinalPosition) {
    const {x, y} = this.getProps(['x', 'y'], useFinalPosition);
    return {x, y};
  }

  draw(ctx) {
    const {x, y, width, options} = this;
	const {sides, radius} = options;
    let angle = (2 * PI) / sides;
    let rad = options.rotation * RAD_PER_DEG;

    ctx.save();
    ctx.beginPath();
    ctx.moveTo(x + Math.sin(rad) * radius, y - Math.cos(rad) * radius);
    for (let i=0; i < sides; i++) {
      rad += angle;
      ctx.lineTo(x + Math.sin(rad) * radius, y - Math.cos(rad) * radius);
    }
    ctx.closePath();
    ctx.stroke();

    ctx.restore();
  }

  resolveElementProperties(chart, options) {
    const {chartArea, scales} = chart;
    const xScale = scales[options.xScaleID];
    const yScale = scales[options.yScaleID];
    let x = chartArea.width / 2;
    let y = chartArea.height / 2;

    if (xScale) {
      x = scaleValue(xScale, options.xValue, x);
    }

    if (yScale) {
      y = scaleValue(yScale, options.yValue, y);
    }

    return {
      x,
      y,
      width: options.radius * 2,
      height: options.radius * 2
    };
  }
}
```

This is the sample, annotation config:

```javascript
plugins: {
	annotation: {
		drawTime: 'afterDraw',
		annotations: {
			trangle: {
				type: 'poligon',
				xScaleID: 'x',
				yScaleID: 'y',
				xValue: 0,
				yValue: 0,
				sides: 3,
				radius: 50,
			},
			pentagon: {
				type: 'poligon',
				xScaleID: 'x',
				yScaleID: 'y',
				xValue: 40,
				yValue: 40,
				sides: 5,
				radius: 50,
			}
		}
	}
}
```

Here is the result:

![poligon](https://user-images.githubusercontent.com/11741250/142998525-50f1d8be-4336-4d26-a060-bcbacd74f7f2.png)

If it sounds good to you, I can create a PR to implement it (but I'd wait for #502 merge in order to re-use some helpers method, like `setBorderStyle` and  `getChartPoint`).
