### ISSUE TITLE
UI Glitch when updating the data

### ISSUE THREAD

**Issue by philfontaine** [chartjs/chartjs-plugin-annotation#446]
When updating the data, the annotations will sometimes appear on the top left corner while the animation is taking place. When the animation is done, the annotation will move to its correct position.

![image](https://user-images.githubusercontent.com/16233697/126689407-e35ff38e-c2ac-4cb9-b424-cfec72c935e3.png)

This behavior can be reproduced right from the samples of the online docs : https://www.chartjs.org/chartjs-plugin-annotation/samples/types/line.html#line

1. Click on `remove data` until there is no more data
2. Click on `add data`

**Comment by kurkle** [comment]
This happens because the "minValue" returns `Infinity` when there is no data. Inifinity us quite far up, but the label is enforced to stay inside chartArea. The last animation step going from infinity to the actual value is still infinite large, that's why it jumps to its final position at last frame. The solution is to prevent infinity.

**Comment by philfontaine** [comment]
@kurkle Maybe this is a way to fix it in this particular example, but I don't thick it actually fixes the real issue. In my actual use case, the problem happens on datetimes with the zoom plugin (so not related to Infinity)

![recording (1)](https://user-images.githubusercontent.com/16233697/130488431-cfa91c52-a14d-473c-897b-5d1145b1f53d.gif)

I understand that the annotation must stay inside the chart, so maybe there isn't any way to really fix this.

**Comment by kurkle** [comment]
@philfontaine ok, I think I found the problem.
