### ISSUE TITLE
Mouse over

### ISSUE THREAD

**Issue by EmilMoe** [chartjs/chartjs-plugin-annotation#48]
I can see there are some mouse events on the annotation, are those for the line, I assume so?

Is it possible to:
* Make the line bolder while the mouse is hovering
* Show a tooltip like for charts while the mouse is hovering

Andd how complicated would this be or what is the easiest strategy?

**Comment by compwright** [comment]
Quite possible, and rather easily. See https://github.com/chartjs/chartjs-plugin-annotation/blob/master/samples/horizontal-line.html

**Comment by kwerle** [comment]
This no longer causes a redraw with the latest chartjs?

**Comment by dnsudhir** [comment]
What about showing as tootip? @compwright

**Comment by C5H8NNaO4** [comment]
The example doesn't seem to work anymore with the latest chart.js.  As soon as I add a `mouseenter/mouseover` event, the `mouseleave/mouseout` event isn't firing anymore. This is probably due to the following error: 

> Unable to preventDefault inside passive event listener invocation.

Setting `this.options.label.enabled = false` doesn't seem to work either. I need to change the chart options directly `chart.options.annotation.annotations[0].label.enabled = false`.

**Comment by Mihailoff** [comment]
https://github.com/chartjs/chartjs-plugin-annotation/blob/8d2239ede9723468a1426b74307ee9ecfc6f8db2/v3-migration.md
> onMouseenter was removed. Use enter instead.
