### ISSUE TITLE
Annotations still broken when using array syntax

### ISSUE THREAD

**Issue by elitastic** [chartjs/chartjs-plugin-annotation#585]
Annotations still look broken when using array syntax, have a look at the following codepen:

https://codepen.io/elitastic/pen/MWEvVYO

Styling is completely different when using array syntax!

Thanks a lot for any feedback!

**Comment by stockiNail** [comment]
I think it's still related to https://github.com/chartjs/Chart.js/pull/9969 (not released yet).

The defaults are not applied because is looking in the `lineAnnotation` (default type) where some options are missing (`backgroundColor`, for instance).

I have tried some workarounds but without success (apart to use the object instead of the array).
@kurkle what do you think?

**Comment by LeeLenaleee** [comment]
What @stockiNail said is true, when using the master of chart.js and the annotation plugin it works fine:
https://codepen.io/leelenaleee/pen/eYGErrm

**Comment by elitastic** [comment]
thank you for your quick replies! I thought by mistake this was fixed by the following workaround:

https://github.com/chartjs/chartjs-plugin-annotation/pull/575

So I'll wait for ChartJs 3.7 release, no problem.

**Comment by LeeLenaleee** [comment]
@elitastic 3.7 has been released and it works fine with the latest released version of annotation plugin for your issue: https://codepen.io/leelenaleee/pen/WNZZPoB

**Comment by elitastic** [comment]
Great news, thanks for the info!
