### ISSUE TITLE
yMax / yMin does not work anymore without explicit boundaries

### ISSUE THREAD

**Issue by jastax** [chartjs/chartjs-plugin-annotation#652]
Hey,

I used to split the chart in 3 colored zones.

```
annotations: {
              first: {
                ...
                type: "box",
                yMin: 30,
              ..
              },
              second: {
                ...
                type: "box",
                yMax: 30,
                yMin: 1,
              ..
              },
              third: {
                ...
                type: "box",
                yMax: 1,
              ..
              },
....
}
```

But now it does not color the graph correctly anymore, unless I add yMax in the first box and yMin in the third box. Those values are dynamic though and I don't want to add boundaries.

Any advice?

Thanks!

**Comment by stockiNail** [comment]
@jastax it's not clear what you are expecting, therefore I have tried to create a sample to understand if the following is what you need:

![issueCoordinates](https://user-images.githubusercontent.com/11741250/150692707-228ba2ef-2919-4af7-9b00-a058059cf90b.png)


If it's correct, try changing the order of the annotations, because using the default coordinates (chart area limitis) the annotations could overlap the others depending on the order how they are defined, as following:

```javascript
annotations: {
  third: {
    ...
    type: "box",
    yMax: 1,
    ...
  },
  first: {
    ...
    type: "box",
    yMin: 30,
    ...
  },
  second: {
    ...
    type: "box",
    yMax: 30,
    yMin: 1,
    ...
  },
....
}
```

**Comment by stockiNail** [comment]
@jastax I made a mistake in the sample. I'm still checking

**Comment by stockiNail** [comment]
@jastax it's not clear what you are expecting, therefore I have tried to create a sample to understand if the following is what you need:

![issueCoordinates](https://user-images.githubusercontent.com/11741250/150693354-b5ae52ba-cb6f-440b-b089-c6185de6737c.png)

If it's correct, try changing the yMin/yMax configuration, as following:

```javascript
annotations: {
  first: {
    ...
    type: "box",
    yMax: 30,
    ...
  },
  second: {
    ...
    type: "box",
    yMax: 30,
    yMin: 1,
    ...
  },
  third: {
    ...
    type: "box",
    yMin: 1,
    ...
  },
....
}
```

Currently the defaults are calculating the yMin/yMax values based on chart area dimensions. but if the yMax is missing, the defaults is `chartArea.bottom` and if yMin is missing, the defaults if `chartArea.top`.

This could be misleading because, if the scale is defined with `reverse: false` (default), yMax is using the minim value of y scale (at `chartArea.bottom`) and for yMin viceversa (at `chartArea.top`).

The above proposal is a workaround. Probably the default calculation should take care about the `reverse` options of the scale.

**Comment by kurkle** [comment]
> Probably the default calculation should take care about the reverse options of the scale.

I disagree, because there could be any number of options in a scale that affects how values are interpreted. But we should improve the documentation. I think min/max are considered to be relative to the top/left origin of the coordinate system.

**Comment by kurkle** [comment]
@jastax what do you mean by "anymore", what version were you using before?

**Comment by stockiNail** [comment]
> . I think min/max are considered to be relative to the top/left origin of the coordinate system.

uhm... I'm not 100% with you. In my opinion, y/xMin or y/xMax are values of the scale (in fact they are calculating using the scale and not the chart area) and not a relative point starting from top/left of chart area.

**Comment by stockiNail** [comment]
> @jastax what do you mean by "anymore", what version were you using before?

@kurkle let's wait for @jastax feedback but I think he meant the plugin for chartjs v2.

See here how it was calculated:

https://github.com/chartjs/chartjs-plugin-annotation/blob/7ef33a9cc349a4ca960ac0f1b709240d0204fa38/src/types/box.js#L37-L45

As you can see, it used chart area to calculate the value of scale at chart area top/bottom and use the value to calculate teh coordinates in the chart (and not how it is now where we are using directly the chart area dimensions).

**Comment by stockiNail** [comment]
> because there could be any number of options in a scale that affects how values are interpreted.

I have to admit that I don't understand it. the `reverse` options  is only changing the order on the scales to represent the datasets, whatever to be the type of the data.

Testing the `reverse` options, we could maintain the x/yMin and x/yMax options coherent with the data configuration of the user.
The reverse options will decide which is the minimum or maximum value on the scale to use as default when x/yMin and x/yMax options are undefined.

**Comment by jastax** [comment]
Hello,

thank you very much for your answers.
I was using 1.0.2 with Chart Js 3.5.1 (I think) before

**Comment by jastax** [comment]
That's great news, thanks.

I won't be able to do it in the next few days but will try to create one after that.
