### ISSUE TITLE
Revise warning if a non-existing scale ID is used?

### ISSUE THREAD

**Issue by joshkel** [chartjs/chartjs-plugin-annotation#662]
I noticed that chartjs-plugin-annotation has started logging several warnings similar to the following for my charts:

> No scale found with id 'y' for annotation 'my-annotation-id'

This appears to be the result of #526. In my case, I'm drawing vertical lines, so I leave all of the Y-related properties (`yAxisID`,  `yMin`, `yMax`) blank. So the fact that a default `y` scale doesn't exist shouldn't matter: I want the default documented behavior of "if `yScaleId` is not resolved, the line will take the entire chart height." (And, without `yMin` or `yMax`, the annotation would take the entire chart dimension regardless.)

Could/should the warning logic from #526 be revised? Instead of warning whenever the configured scale doesn't exist, it could warn if the configured scale doesn't exist and either of the following are true:

* The configured scale is not the default value.
* The annotation has configured properties for the scale's associated values (`value` and `endValue` for `scaleID`; `xMin`, `xMax`, `xValue` for `xScaleID`; `yMin`, `yMax`, `yValue` for `yScaleID`).

**Comment by stockiNail** [comment]
@joshkel in my opinion, it could make sense to add those additional tests, before emitting the message.

**Comment by kurkle** [comment]
I dislike changing the behavior based on if the ID is default or not. But in case there is no value configured for given axis, the warning should be omitted.

**Comment by stockiNail** [comment]
> @joshkel in my opinion, it could make sense to add those additional tests, before emitting the message.

I agree with you but we could not set any defaults scale ids because they are already defined in the controllers.

It should be enough to change the following:

https://github.com/chartjs/chartjs-plugin-annotation/blob/ccc89987a42c63f0c84d012e2fbdcc6e119ed06c/src/annotation.js#L69

in 

```javascript
verifyScaleOptions(annotations, chart.options.scales);
```

Passing the options (and leveraging on fallback) you could have all defaults scales even if not defined by user.

I have tested and it seems working.

**Comment by stockiNail** [comment]
Just for sharing, I have tested the following chart config:

```javascript
{
  type: 'scatter',
  options: {
    plugins: {
      annotation: {
        annotations: {
          noWarn: {
            type: 'line',
            yMin: 5,
            yMax: 5,
          }
        }
      }
    }
  }
}
```

Maybe there some other use cases.

**Comment by stockiNail** [comment]
> So the fact that a default y scale doesn't exist shouldn't matter:

@joshkel About the above sentence I have some doubts.

Every controller should have default scales and then default ids (x and y). In the plugin, the defaults are x/y  for x/yScaleID.

Doing some tests, I see that the warning, you are receiving, could occur only when no datasets are configured in the chart (and only in this condition). Could you share a sample (or codepen) in order to reproduce better the issue?

**Comment by stockiNail** [comment]
I have prepared a codepen https://codepen.io/stockinail/pen/yLPNYQM which is trying to simulate the use case.

`x/yScaleID` are not set and no scales are configured. No warning message is emitted. But if you remove the datasets node, the log message will appear because `chart.scales` is not populated.

**Comment by joshkel** [comment]
@stockiNail See https://codesandbox.io/s/silly-jang-rwwfi; I'm seeing the problem if I my datasets are all configured to use custom axes, such that the default axis is neither created nor used.

**Comment by stockiNail** [comment]
@joshkel Thank you very much and I'm sorry if I didn't catch the use case, you mentioned,, since the beginning. I have submitted a PR which is implementing:

> The annotation has configured properties for the scale's associated values (xMin, xMax, xValue for xScaleID; yMin, yMax, yValue for yScaleID).

About `value and endValue for scaleID;`  is not checked because there isn't any `scaleID` default value therefore you can not omit it from the configuration if you want to use it.

**Comment by joshkel** [comment]
> Thank you very much and I'm sorry if I didn't catch the use case.

No problem. Thanks for the discussion and fix, @stockiNail (and @kurkle).
