### ISSUE TITLE
Vertical Line In Wrong Location

### ISSUE THREAD

**Issue by FGAM-US** [chartjs/chartjs-plugin-annotation#685]
Chart.js v3.7.0
chartjs-plugin-annotation v1.3.1

I've added a vertical line at location 22 as shown here:
> annotations: { 'a1': { type:'line'**,xMin:22,xMax:22**,borderColor:'forestgreen',borderWidth:2 }

On some charts, this works fine, however on other charts, the line is misplaced.  Here is an example...

This is the chart after being fully rendered; note the absence of the vertical green line at position 22:

![image](https://user-images.githubusercontent.com/98418400/153725893-ca91e1ab-7ba2-4513-81b1-b58480ab846c.png)

After several attempts, I was able to capture a screenshot during the chart's animation -- this image shows the vertical green line is present, but it is far off to the right:

![image](https://user-images.githubusercontent.com/98418400/153726045-abd3e69d-76ff-4cac-828f-38a6bf847c08.png)

This is the full code:
![image](https://user-images.githubusercontent.com/98418400/153726146-0e751842-1115-4fce-801c-eadf17d8b026.png)

**Comment by stockiNail** [comment]
@FGAM-US this is happening because the scale X is a category scale and using a number to locate the annotation, this number is used as index of label.

In your case, setting 22, it means the value on the scale at index 22. 
I have created a codepen, where using xMin: 5, xMax: 5 (the index of the value that I want in the labels) should work:

https://codepen.io/stockinail/pen/jOaLEYV

**Comment by FGAM-US** [comment]
Excellent!  Thank you for the quick response, @stockiNail  I'll look into that.  Have a great weekend!  :)
