### ISSUE TITLE
Modifying annotation with multiple charts on same page make all charts same

### ISSUE THREAD

**Issue by crabouif** [chartjs/chartjs-plugin-annotation#710]
Hi,

In my project I should have multiple charts on the same page. I want to draw a vertical line on the selected scale X value and when the selected X scale value change, change the vertical line on the charts (all charts have same X scale and labels).

So for that I use annotations and it work fin if I have only one chart on page. But if I have multiple charts, when I modify the selected X value, all charts on page become identical. It's like the canvas become same instance ?!

Project properties:
- Angular
- ng2-charts 3.0.8
- chart.js 3.7.1
- chartjs-plugin-annotation 1.4.0

When I change the selected X value, I do this code:
```ts
      Object.values(Chart.instances).forEach(i => {
            i.config.options.plugins.annotation = {
                annotations: {
                    currentXvalue: {
                        type: 'line',
                        borderWidth: 1,
                        scaleID: 'x',
                        label: {
                            enabled: this.currentLogLineShowLabel,
                            content: newLabel,
                            position: 'start'
                        },
                        value: selectedXvalue
                    }
                }
            };
            i.update('none');
        });
``` 

Also I put different id on each canvas to check that each instance is different, and that was.

Any idea ?

**Comment by stockiNail** [comment]
@crabouif I'm not sure if I caught your use case.

Anyway here is a codepen https://codepen.io/stockinail/pen/MWrWJWq

There are 2 charts in the same page. When you click on the chart area, in one of the two, the other will be updated setting the same annotation label, with the same value.

I used your function, even if I changed `i.config.options` in `i.options` and change the variables that I don't know where are set (and how) in your code, like `selectedXvalue` and `this.currentLogLineShowLabel`).

Anyway, the 2 charts are drawn and shown correctly, maintaining their differences.

Could you prepare a codepen of jsfiddle in order to reproduce what you have?

I have also the feeling that if you want to change annotations on all charts by a value, maybe you couldn't set the annotation every time the value is changed but you could configure the annotation on the chart with scriptable options and updating the charts you could get and provide the new value.

**Comment by crabouif** [comment]
It was my fault I has shared static configuration that was shared between charts and within the data array has same reference...

Sorry to burn a bit your time.

I close the issue.

**Comment by stockiNail** [comment]
> Sorry to burn a bit your time.

No problem! It's important you solved.
