### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'borderWidth') in Angular 16

### ISSUE THREAD

**Issue by Venators** [chartjs/chartjs-plugin-annotation#953]
Hello 👋🏻

I utilised charts-plugin-annotation in an Angular project, and it worked without issue under Angular 15, but since migrating to Angular 16, the annotation plugin errors and breaks the rendering of the chart it plugged into - I haven't found a similar issue logged - and this is the error I receive:
`loader.interceptor.ts:25 ERROR TypeError: Cannot read properties of undefined (reading 'borderWidth')
    at resolveLabelElementProperties (chartjs-plugin-annotation.esm.js:2141:31)
    at LineAnnotation.resolveElementProperties (chartjs-plugin-annotation.esm.js:1948:29)
    at updateElements (chartjs-plugin-annotation.esm.js:2717:32)
    at Object.afterUpdate (chartjs-plugin-annotation.esm.js:2894:5)
    at callback (helpers.segment.js:79:19)
    at PluginService._notify (chart.js:5091:25)
    at PluginService.notify (chart.js:5074:29)
    at Chart.notifyPlugins (chart.js:6356:30)
    at Chart.update (chart.js:5917:14)
    at Chart.<anonymous> (chart.js:5659:48)`
And the annotation plugin method where the error occurs:
![image](https://github.com/user-attachments/assets/cfeff390-c8e3-4655-be73-e3dd4f7e1381)

My configuration of the plugin is like so:
![image](https://github.com/user-attachments/assets/d22b5835-63f5-47e5-bc8a-cc1cd83d90b4)
And it hasn't changed through the update, which touched the following packages:
- Angular 15.2.9 => 16.2.12
- ng2-charts 3.1.2 => 5.0.4
- chart.js 3.9.1 => 4.4.3
- chartjs-plugin-annotation 2.2.1 => 3.0.1

After discovering the issue, I've also tried chartjs-plugin-annotation 3.1.0 and chart.js 4.4.4/4.4.5, but the issue persists. Any help on this would be appreciated if someone can see where I'm going wrong or has also encountered this themselves and found a solution?

**Comment by stockiNail** [comment]
@Venators this issue sounds to be related to the missing registration of the plugin to Chartjs.. How are you register it?

**Comment by tanrikut** [comment]
Hi,

I have the same problem with Chartjs 4.4.7 version in Angular 18. But I don't think the problem is related to Angular version. It seems like a problem in annotation plugin. 

If you add a `label` to your options, it seems to bypass this error. But this resulted into another error:

![image](https://github.com/user-attachments/assets/953e8419-722e-47f7-a037-d2c0a41a63c6)

**Comment by stockiNail** [comment]
@tanrikut thank you for feedback! adding a label annotation, the fallback is not completely invoked and this is why you don't have that issue.
How are you registering the plugin to Chart.js?

**Comment by tanrikut** [comment]
```
import ChartDataLabels from 'chartjs-plugin-datalabels';
import Annotations from 'chartjs-plugin-annotation';

plugins = [ChartDataLabels, Annotations];
```

I am using Primeng Chart component (which is actually a Chartjs binder).
```
<p-chart type="bar" [data]="chartData" [options]="chartOptions" [plugins]="plugins" ></p-chart>
```

Please note that ChartDataLabels plugin is working with this setup

**Comment by stockiNail** [comment]
@tanrikut your registration is not correct and this is the reason why your getting the error.

The annotation plugin cannot be registered to Chart.js as an `inline` plugin.
`Inline` plugins are the plugins which are defined in the configuration of a specific  chart instance.

The `inline` plugins are not consuming registration events (implementing the registration hooks) which are needed for annotation plugin.

See documentation https://www.chartjs.org/chartjs-plugin-annotation/latest/guide/ and also the README https://github.com/chartjs/chartjs-plugin-annotation/blob/master/README.md

See Bundles chapter how to do it: https://www.chartjs.org/chartjs-plugin-annotation/latest/guide/integration.html#bundlers-webpack-rollup-etc

The datalabels plugin can work as `inline` plugin because it doesn't implement the registration hooks of Chart.js.

I don't know how PrimeNG Chart is working and if enabling the global plugins.

**Comment by stockiNail** [comment]
@tanrikut let me know if it will work using `Chart.register(annotationPlugin);`

**Comment by tanrikut** [comment]
@stockiNail 

it worked (even with primeng). thanks for your help and plugin.
