### ISSUE TITLE
Box not aligning correctly on bar chart

### ISSUE THREAD

**Issue by kaiukdevelopment** [chartjs/chartjs-plugin-annotation#98]
Hi, I have added two box annotations however they are not working to how I expect them to be.
Below is my code:
```
           annotation: {
              annotations: [{
                type: 'box',
                id: 'hLine',
                xScaleID: 'x-axis-0',
                yScaleID: 'y-axis-0',
                xMin: "005",
                xMax: "006",
                yMax: 50000,
                yMin: 50000,
                borderColor: 'red',
                borderWidth: 5,
                backgroundColor: 'green'
              },
              {
                type: 'box',
                xScaleID: 'x-axis-0',
                yScaleID: 'y-axis-0',
                xMin: "006",
                xMax: "006",
                yMax: 60000,
                yMin: 60000,
                borderColor: 'red',
                borderWidth: 5,
                backgroundColor: 'green'
              }]
            } 
```

See Attached image.

Firstly the xMin is starting from the middle of '005' and ending in the middle of '006'. I also tried putting the xMin and xMax as the same ID however it disappears. 

![capture](https://user-images.githubusercontent.com/13997981/33275832-a51bd35a-d38b-11e7-8a82-9438fe5e81a8.PNG)

**Comment by jonathan-deng-ck** [comment]
I am currently running into this issue too for categorical x-axis values.  The edges of the box align with the middle of the bar chart instead of the left and right edges.

**Comment by jonathan-deng-ck** [comment]
Downgrading to chart.js@2.6 seems to solve this issue, but the box alignment doesn't seem compatible with v2.7

**Comment by TBVanderley4545** [comment]
Best solution I had was to create a secondary x axis then set its display to false so that the labels wouldn't show at the bottom of the chart. I had 5 bars that I needed in my chart, so I made my second x-axis have the labels [1, 2, 3, 4, 5, 6] (don't use string values, just used ints in mine). I charted all of my data to have xAxisID as the primary-x. For the box annotations, I used xScaledID: "secondary-x" (or whatever you name your secondary x-axis). I then gave 

box 1:
xMin: 1
xMax: 2

box 2:
xMin: 2
xMax: 3

box 3:
xMin: 3
xMax: 4

box 4:
xMin: 4
xMax: 5

box 5:
xMin: 5
xMax: 6

I know this is a super late answer, but hopefully it helps someone else. If you need more clarification in my answer, just respond to me, and I can try to help more.

**Comment by Techn1x** [comment]
I've run into this issue too, looks like ChartJS 2.7.0 changed something. Clever idea @TBVanderley4545

**Comment by TBVanderley4545** [comment]
@Techn1x Thanks, Hope it helped solve your problem!

**Comment by curiousPup** [comment]
Facing same issue

**Comment by dariobednarski** [comment]
Facing same issue. Box shouldn't start in the middle of index.

**Comment by etimberg** [comment]
Still an issue in 1.0.0-beta.4 https://jsfiddle.net/prmnh1v3/

**Comment by kurkle** [comment]
can use half index values: https://jsfiddle.net/e4b07rtc/

**Comment by kurkle** [comment]
https://www.chartjs.org/chartjs-plugin-annotation/samples/charts/bar.html
